### ISSUE TITLE
How to catch AJAX errors?

### ISSUE THREAD

**Issue by andrasgalli** [bkdotcom/PHPDebugConsole#27]
Hi! I am unable to catch errors, when a call was made from javascript (or other). The call is processed by php, and the response is a json, but nothing is added by the phpdebugconsole.
Should I make something in the configuration?

**Comment by bkdotcom** [comment]
@andrasgalli 
My apologies.  I just noticed this "new" issue
I assume you're using the 2.3.x release ?
both 2.3 and the dev branch will automatically output chromeLogger headers with ajax responses

There are browser plugins for Chrome, Firefox, etc
here's one for Chrome
https://chrome.google.com/webstore/detail/server-log/lophlnbmepajcpfhafaciibembckdpih

let me know if you encounter any issues

Thanks for trying out my tool..  I hope to release a 3.0 beta version _very_ soon
