### ISSUE TITLE
Don't override standard logging

### ISSUE THREAD

**Issue by strider72** [bkdotcom/PHPDebugConsole#40]
I create a Debug object "$console" on my Dev site so I can quickly shoot a value to the browser console.  But for some reason the mere existence of this Debug object overrides standard logging of errors.  If my page gets an error it doesn't get logged *anywhere*.

Is this a bug or a setting somewhere?  If there's a way for me to turn this behavior off, that would be great. Otherwise it totally kills the usefulness of this Class because I have to leave it turned off.

**Comment by bkdotcom** [comment]
@strider72 
try instantiating with the following config
```
array(
    'errorReporting' => 0,  // don't handle errors of any type
)
```
And/or there is a per-error 'continueToNormal' option that can be set via event subscriber
```
$debug->eventManager->subscribe('errorHandler.error', function (\bdk\PubSub\Event $error) {
    $error['continueToNormal'] = true;
});
```

The expected behavior is to not log errors if the Debugger is _enabled_ / you are debugging.  As the errors _should_ be output with the log .     I will double-plus confirm errors are logged in the master branch

**Comment by strider72** [comment]
Awesome. I hope that covers it.

Missing from my initial report was the fact that error logging via the `error_log()` function did indeed log properly. So based on that, it seems your discovery is indeed the bug I was seeing.

Thanks!

**Comment by strider72** [comment]
So... just to be clear, when the fix is released, all I have to do is add `'errorLogNormal'=>true` to the config array -- is that correct?

**Comment by bkdotcom** [comment]
@strider72    you are correct  
Sorry... the fix has been on the master branch for quite some time.
finally pushed a new "release" with it though:
https://github.com/bkdotcom/PHPDebugConsole/releases/tag/v3.0b1

`composer require bdk/debug:3.0b1 --update-no-dev`
