### ISSUE TITLE
Request Headers problem with php 8.1.15

### ISSUE THREAD

**Issue by rgilsimoes** [bkdotcom/PHPDebugConsole#55]
After a lot of testing I believe there is a problem when using php 8.1.15.
When setting route to "chromeLogger" and enabling requestHeadersOutput there is always this sequence of errors:

[proxy_fcgi:error] [pid 47499:tid 140439541749504] [client ... ] Premature end of script headers: report_novos_cartoes.php, referer: https://www......eu/.../
[proxy_fcgi:error] [pid 47499:tid 140439541749504] [client ... ] AH01070: Error parsing script headers, referer: https://www....eu/.../

I messed with a lot of buffer sizes and so on, but the only solution was to change to php 8.0.23 and now it is working.

**Comment by bkdotcom** [comment]
I will take investigate, but this smells like the headers grew too big for the proxy server
Have you tried ServerLog  (http://bradkent.com/php/debug#routeServerLog)

it seems to have been created to address the header size limitations of ChromeLogger...

Essentially the log is written to a json file..  a url to that file is output in the response headers..    A browser plugin then requests the log.

**Comment by rgilsimoes** [comment]
Hi @bkdotcom ! 
I've tried ServerLog but could not get any output from the browser plugin :-/ not too much info about it also.

As far as the size limitations what I've also found was that when setting the max Header Size on bdkDebug the ChromeLogger yields an error saying it could not allocate X Kb for logging.

**Comment by rgilsimoes** [comment]
Hello @bkdotcom!
I've tried both Server Log chrome extensions and found out the following:
This "ServerLog" extension https://chrome.google.com/webstore/detail/server-log/lophlnbmepajcpfhafaciibembckdpih works fine when you open the related dev panel.

As this "Server Log" extension https://chrome.google.com/webstore/detail/serverlog/ghmhlknahaejhdlobgpaoocmjlhgmcci does not work because it asks for a "key" in order to authenticate to the server.

I've tried added the same key to both php Debug and the extension but it does not seem to work.

**Comment by bkdotcom** [comment]
the "key"used in the 2nd extension is unrelated to PHPDebugConsole's key...
I haven't installed the extension, but it appears it may be optional and used in conjunction with a serverside library by the same author..

**Comment by bkdotcom** [comment]
I'm going to close this issue soon as It seems to be server configuration related

did you have any luck with it?

perhaps fast-cgi related?

I did find these "articles" regarding "Premature end of script headers" :

* https://serverfault.com/questions/265752/premature-end-of-script-headers-mod-fcgi
* https://www.knownhost.com/kb/what-is-the-premature-end-of-script-headers-php-error/
